Update nodegit dependency
The nodegit dependency previously used did not work with the latest
nodejs. Updating to the latest available nodegit fixes relevant errors.

Fixes "Error: Cannot find module '../build/Debug/nodegit.node'"
Closes #15